### ISSUE TITLE
@Inject constructor and the class it is defined in must be public/internal.

### ISSUE THREAD

**Issue by kirich1409** [yandex/yatagan#21]
I have a Kotlin class like this
```kotlin
class @Inject internal constructor(...)
```

The class isn't valid for Yatagan. It can be fixed with
```kotlin
internal class @Inject internal constructor(...)
```
or
```kotlin
class @Inject constructor(...)
```

In Dagger 2 the class is valid.

**Comment by Jeffset** [comment]
`public class SomeClass @Inject internal constructor(..)` should be (and as far as I can tell - is) a valid construct for Yatagan. If the Yatagan gives an error in such case, please, provide more info.

**Comment by kirich1409** [comment]
Can't reproduce again
