### ISSUE TITLE
Support build on Windows (Build issue, illegal escape)

### ISSUE THREAD

**Issue by mironoff2007** [yandex/yatagan#69]
I've tryed to run tests. I got this error. Please help.
Seems like escaping slash is missed
![image](https://github.com/yandex/yatagan/assets/18057056/1fcdb1b3-d34f-4982-a07c-f6b5dd0c7af2)

**Comment by Jeffset** [comment]
Thanks for the issue!

Well, I never checked if yatagan can be built on Windows (you appear to use that platform to assemble it, right?). Sadly, the build is broken on Windows. As of now, there's no simple workaround, **the project can be built on Linux only** (MacOS is untested as well).

Maybe I should support build on Windows. If I do, I'll link the PR to this issue.
